[build]
  functions = "netlify/functions"
  publish = "." # Eğer HTML dosyaların ana dizindeyse nokta kalsın

[functions]
  included_files = ["netlify/functions/**/*.js"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

[dev]
  framework = "#static"
  command = "echo dev"
  targetPort = 3999
